#CICLO6
#CarolAgyelaGonzalezOchoa

ANIMALES=["GARZA","RINOCERONTE","PUMA","JAGUAR","AGUILA","ANGUILA","PES","SERPIENTE","GATO","PERRO"]
for letra in ANIMALES:
    print("ALGUNOS ANIMALES SON: ",ANIMALES)
