#CICLO9
#CarolAgyelaGonzalezOchoa

DEPORTES=["VOLEIBOL","FUTBOL","BASQUETBOL","GIMNACIA","RUGBY","NATACION","TENIS","BEISBOL","CICLIMSMO","BALONCESTO"]
for letra in DEPORTES:
    print("ALGUNOS DEPORTES SON: ",DEPORTES)
